-- MySQL Script generated by MySQL Workbench
-- Thu Nov 20 14:22:48 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgp_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgp_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgp_bd` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sgp_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgp_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgp_bd` DEFAULT CHARACTER SET utf8 ;
USE `sgp_bd` ;

-- -----------------------------------------------------
-- Table `sgp_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgp_bd`.`usuarios` (
  `nome_usuario` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`nome_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgp_bd`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgp_bd`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `usuarios_nome_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`, `usuarios_nome_usuario`),
  INDEX `fk_produtos_usuarios_idx` (`usuarios_nome_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_usuarios`
    FOREIGN KEY (`usuarios_nome_usuario`)
    REFERENCES `sgp_bd`.`usuarios` (`nome_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sgp_bd` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
