-- MySQL Script generated by MySQL Workbench
-- Thu Dec 11 07:36:54 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sgp_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgp_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgp_bd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema sgp_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgp_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgp_bd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sgp_bd` ;

-- -----------------------------------------------------
-- Table `sgp_bd`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgp_bd`.`usuarios` (
  `nome_usuario` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`nome_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgp_bd`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgp_bd`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `usuarios_nome_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`, `usuarios_nome_usuario`),
  INDEX `fk_produtos_usuarios_idx` (`usuarios_nome_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_produtos_usuarios`
    FOREIGN KEY (`usuarios_nome_usuario`)
    REFERENCES `sgp_bd`.`usuarios` (`nome_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgp_bd`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgp_bd`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `usuarios_nome_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`, `usuarios_nome_usuario`),
  INDEX `fk_clientes_usuarios1_idx` (`usuarios_nome_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_usuarios1`
    FOREIGN KEY (`usuarios_nome_usuario`)
    REFERENCES `sgp_bd`.`usuarios` (`nome_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgp_bd`.`despesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgp_bd`.`despesas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `data_compra` DATE NOT NULL,
  `valor_total` FLOAT NOT NULL,
  `usuarios_nome_usuario` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`, `usuarios_nome_usuario`),
  INDEX `fk_despesas_usuarios1_idx` (`usuarios_nome_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_despesas_usuarios1`
    FOREIGN KEY (`usuarios_nome_usuario`)
    REFERENCES `sgp_bd`.`usuarios` (`nome_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sgp_bd`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgp_bd`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_nome_usuario` VARCHAR(50) NOT NULL,
  `produtos_id` INT NOT NULL,
  `clientes_id` INT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_nome_usuario`, `produtos_id`, `clientes_id`),
  INDEX `fk_pedidos_usuarios1_idx` (`usuarios_nome_usuario` ASC) VISIBLE,
  INDEX `fk_pedidos_produtos1_idx` (`produtos_id` ASC) VISIBLE,
  INDEX `fk_pedidos_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_usuarios1`
    FOREIGN KEY (`usuarios_nome_usuario`)
    REFERENCES `sgp_bd`.`usuarios` (`nome_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_produtos1`
    FOREIGN KEY (`produtos_id`)
    REFERENCES `sgp_bd`.`produtos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `sgp_bd`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sgp_bd` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
